### ISSUE TITLE
Add a `get_all` method to `RootEntity`  to get the all the stored data

### ISSUE THREAD

**Issue by andrea-mucci** [minos-framework/minos-python#156]
**Is your feature request related to a problem? Please describe.**
If we need to ask for all the RootEntities that are stored, wich kind of method we use? at the moment the two queriies method are get and find but the get_all() method, for example is not present

**Describe the solution you'd like**
add a method get_all() that return the entire RootEntities set

**Describe alternatives you've considered**
at the momento have no alternatives

**Comment by garciparedes** [comment]
Hi @andrea-mucci!

Currently, we have a way to do that through the `find` method and `Condition.TRUE`, which is satisfied by all the root entities stored on the database. 

But I agree with you, adding a `get_all` method will provide the same functionality in a more intuitive way.
