### ISSUE TITLE
Certificates for minos.run?

### ISSUE THREAD

**Issue by vsoch** [minos-framework/minos-python#183]
Hi! I'm wanting to read your site/ docs, but my browser doesn't let me go there:

![image](https://user-images.githubusercontent.com/814322/153127330-5571910b-8c9e-463c-b4d9-ce3df37f3eee.png)

And I'm hoping you might be able to consider adding https for a secure connection. Thank you!

**Comment by andrea-mucci** [comment]
The website certificate was added, we can close the following issue
