### ISSUE TITLE
Test with tavern, the query service set the 'name' parameter with the name of the aggregate

### ISSUE THREAD

**Issue by andrea-mucci** [minos-framework/minos-python#194]
**Describe the bug**
i have set a model with 

```python

class Product(Base):
    __tablename__ = 'product'

    id = Column(Integer, primary_key=True)
    uuid = Column(String(60))
    name = Column(String(80))
    description = Column(Text, nullable=True)
    picture = Column(String(120), nullable=True)
    price_id = Column(Integer, ForeignKey('price.id'))
    price = relationship("Price", backref=backref("product", **uselist=False))

```

the command query receive the params from the request and 
put the name of the aggregate class route in name parameter

**To Reproduce**
create a model with an attribute called name
send as parameter the name to the POST
do a GET

**Additional context**
From the Tavern test suite i will get the following response

```python

{'id': '1', 'uuid': '695c5b8e-b47f-4d55-9c60-addb2eb384da', 'name': 'src.aggregates.Product', 'description': 'Product One in our catalog', 'picture': 'images/product.jpeg', 'price_id': '1'}

```

**Comment by garciparedes** [comment]
Hi @andrea-mucci! 

The reason is that a collision between the `minos.aggregate.Event.name` attribute, which contains the `minos.aggregate.RootEntity`'s class name and the `name` of your concrete `RootEntity`'s implementation is produced.

To avoid these kind of collisions is better to access the field differences of the event through the `minos.aggregate.Event.get_one()` method.

In any case, we can analyze this case to provide an easier accessing strategy.

**Comment by andrea-mucci** [comment]
Thanks you so much

so to get the event content i have to ask `minos.aggregate.Event.get_one()`

this method will return a dictionary with all the attributes, is that correct?

**Comment by andrea-mucci** [comment]
Hi

```python
 @enroute.broker.event("ProductCreated")
  async def product_created(self, request: Request) -> None:
      """Handle the Product creation events.

      :param request: A request instance containing the aggregate difference.
      :return: This method does not return anything.
      """
      event: Event = await request.content()
      content = event.get_one()
      self.repository.add(content)
```

this is the code for the "ProductCreated" handler and now the code raise an error

```
2022-02-12 18:19:16 [T:MainThread] ERROR:minos.networks.brokers.dispatchers.impl: Raised a system exception: TypeError("get_one() missing 1 required positional argument: 'name'")
eboutique-product-1     | Traceback (most recent call last):
eboutique-product-1     |   File "/usr/local/lib/python3.9/site-packages/minos/networks/brokers/dispatchers/impl.py", line 153, in _wrapper
eboutique-product-1     |     response = await response
eboutique-product-1     |   File "/usr/local/lib/python3.9/site-packages/minos/saga/middleware.py", line 42, in transactional_command
eboutique-product-1     |     return await inner(request)
eboutique-product-1     |   File "/usr/local/lib/python3.9/site-packages/minos/networks/decorators/builders.py", line 170, in _wrapper
eboutique-product-1     |     response = await response
eboutique-product-1     |   File "/usr/local/lib/python3.9/site-packages/minos/networks/decorators/callables/handlers.py", line 112, in _wrapper
eboutique-product-1     |     response = await response
eboutique-product-1     |   File "/usr/local/lib/python3.9/site-packages/src/queries/services.py", line 50, in product_created
eboutique-product-1     |     content = event.get_one()
eboutique-product-1     | TypeError: get_one() missing 1 required positional argument: 'name'

```

which kind of name I have to pass?
think you this is somethind friendly to undestand?

**Comment by garciparedes** [comment]
The `get_one` method requires the `name` of the field you want to get from the event.

**Comment by andrea-mucci** [comment]
Ok, 

now

the Product Entity have the following atttributes

```python

class Product(RootEntity):
    """Product RootEntity class."""
    title: str
    description: str
    picture: str
    price: Price
    categories: ValueObjectSet[Category]

```

if i will use the get_one() method how i get the price attribute information?

i mean have access to price entity with

```python

price_currency = event.get_one('price.currency')

```

is that correct?

**Comment by garciparedes** [comment]
The dot accessing is not currently possible, but I think it could be a really interesting feature (also to be consistent with the `minos.aggregate.Condition` behavior, that already support this functionality).

The way to do that now is:
```python
price = event.get_one('price')
currency = price.currency
```

Also, we could refactor the `get_one` behavior and also provide access to the `uuid`, `version`  and `updated_at` fields. 🙂

**Comment by andrea-mucci** [comment]
cool,

thank you, we have to consider this feature in next releases

**Comment by garciparedes** [comment]
This bug is closely related to #219
