### ISSUE TITLE
Event class modify get_one and get_all method

### ISSUE THREAD

**Issue by andrea-mucci** [minos-framework/minos-python#195]
**Describe the bug**
The Event have two method to retrieve the content:
``get_one()``and ``get_all()``
those method are not descriptive of which kind os reason are used.
a propose to modify to:

``get_attr()``
and

``get_attrs()``

**Comment by andrea-mucci** [comment]
Hi @vladyslav-fenchak i will reopen the issue because the @garciparedes comment that have would be a better idea to call the new methods get_field and get_fields
in a certain way those new definitions are more compliant with the concept of Fields.
So, maybe we can redo the work?

**Comment by andrea-mucci** [comment]
@vladyslav-fenchak before commit the code, take care of the deprectation warning that the methods get_one and get_all must return

the correct principle for deprecation messages are:

```python
import logging
import warnings
....
logger = logging.getLogger(__name__)
...
warnings.warn("The derprecation warting message", DeprecationWarning)
```

**Comment by vladyslav-fenchak** [comment]
Created PR #225
