### ISSUE TITLE
Change Aggregate test for Event get_one() and get_all()

### ISSUE THREAD

**Issue by vladyslav-fenchak** [minos-framework/minos-python#205]
Change tests and call get_attr() and get_attrs().
Related to #195

**Comment by garciparedes** [comment]
Hi @andrea-mucci and @vladyslav-fenchak!

I think `get_field` and `get_fields` is a better choice as we use the word `Field` instead of `Attr` for the field class (as you can see at `minos.aggregate.Field`).

Could you consider these names instead of `get_attr` and `get_attrs`?
