### ISSUE TITLE
Add decorators to `config` file

### ISSUE THREAD

**Issue by vladyslav-fenchak** [minos-framework/minos-python#232]
Example:
We define all the decorators that we want to be loaded.
```python
...
decorators:
   rest: minos.plugins.rest_aiohttp.RestEnroute
   other: minos.plugins.other.AnotherClass
...
```

**Comment by garciparedes** [comment]
This issue is closely related to https://github.com/minos-framework/minos-python/issues/235

**Comment by garciparedes** [comment]
I'm proceeding to close this PR as it is not currently factible to load decorators from the configuration file...
