### ISSUE TITLE
`AUTHORS.md`, `HISTORY.md` and `LICENSE` installed outside the packages

### ISSUE THREAD

**Issue by albamig** [minos-framework/minos-python#416]
We have been facing an issue while downgrading packages within our Docker images related to `AUTHORS.md` not being found.

The problem is that the [following `pyproject` configuration](https://github.com/minos-framework/minos-python/blob/0fdd4c91439861e1bcb652cbb4489c6a661a9668/packages/core/minos-microservice-common/pyproject.toml#L26-L30) adds those files to the wheel distribution but outside the package itself.
If you [download the wheel](https://files.pythonhosted.org/packages/17/58/d04dfe1532d113acbb5c0f2e292b4d756445cdfdd7990e19f7f6d5694c1b/minos_cli-0.4.0-py3-none-any.whl) and take a look, they are outside of `minos`. 
Another way to see the problem is by running `pip -V` and moving to the installation directory. The files are there among each other package.

Since the `LICENSE` already gets imported within the wheel distribution info and the other packages aren't actually important for distribution, I propose to delete that `pyproject` configuration.

**Comment by garciparedes** [comment]
This issue is closely related to https://github.com/python-poetry/poetry/issues/2015

**Comment by garciparedes** [comment]
I'll fix this issue following a similar approach to https://github.com/pavdmyt/yaspin/pull/135

**Comment by cmungall** [comment]
Hello, I arrived here from the linked poetry issue as I am having a similar issue to the one you resolved.

Did you fix using the magical `sdist` work to your satisfaction?

I noticed that when I installed minos-microservice-cqrs there is no HISTORY.md file included at all,

The source distribution looks like this:

tar -ztf ~/Downloads/minos-microservice-cqrs-0.7.0.tar.gz
minos-microservice-cqrs-0.7.0/AUTHORS.md
minos-microservice-cqrs-0.7.0/HISTORY.md
minos-microservice-cqrs-0.7.0/LICENSE
minos-microservice-cqrs-0.7.0/README.md
minos-microservice-cqrs-0.7.0/minos/cqrs/__init__.py
minos-microservice-cqrs-0.7.0/minos/cqrs/exceptions.py
minos-microservice-cqrs-0.7.0/minos/cqrs/handlers.py
minos-microservice-cqrs-0.7.0/minos/cqrs/services.py
minos-microservice-cqrs-0.7.0/pyproject.toml
minos-microservice-cqrs-0.7.0/setup.py
minos-microservice-cqrs-0.7.0/PKG-INFO

with the files at the top level

the wheel omits these altogether:

tar -ztf ~/Downloads/minos_microservice_cqrs-0.7.0-py3-none-any.whl 
minos/cqrs/__init__.py
minos/cqrs/exceptions.py
minos/cqrs/handlers.py
minos/cqrs/services.py
minos_microservice_cqrs-0.7.0.dist-info/LICENSE
minos_microservice_cqrs-0.7.0.dist-info/WHEEL
minos_microservice_cqrs-0.7.0.dist-info/METADATA
minos_microservice_cqrs-0.7.0.dist-info/RECORD

is this what you intended?

**Comment by albamig** [comment]
Right! That's what we meant to do.

All of our Minos packages (cqrs, common, networks...) have those files. We don't mind to put them within the `sdist` because we never install from it. The problem comes just when putting them within the `wheel`, since if more than one of Minos packages get installed using `pip`, there is a conflicting overriding of those files at the root level.

Does this solve your issue? Don't hesitate to ask further!
