### ISSUE TITLE
Has this project been discontinued? 

### ISSUE THREAD

**Issue by zzhuf** [minos-framework/minos-python#646]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zzhuf** [comment]
Has this project been discontinued? Will we continue to develop updates? I have used version 0.7.0 and the example is no longer usable. Perhaps I need to change the content of many configuration files because many methods have changed their names during submission, but the configuration files in the example have not been changed yet. I am not sure if this project will continue to be updated.

**Comment by snowienator** [comment]
Looking at @garciparedes his profile and opening his [curriculum-vitae](https://github.com/garciparedes/curriculum-vitae) repo.. I think he no longer maintains this project.. Sad..
